name: Basic Commands

on:
  push:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Current Directory 
        run: pwd
      - name: List files
        run: ls -la
      - name: Date
        run: date


      - name: Print Message
        run: echo "Hello from GitHub Actions!"
